name       : cura
version    : 3.1.0
release    : 4
source     :
    - https://github.com/Ultimaker/Cura/archive/3.1.0.tar.gz : b109310a9999df40cc977afaede1217d7574c8fc4a2a2a01a1e957ee8e7fb07f
license    : LGPL-3.0
component  : office
summary    : 3D printer / slicing control software
description: |
    Cura is a project which aims to be an single software solution for 3D
    printing. While it is developed to be used with the Ultimaker 3D printer,
    it can be used with other RepRap based designs.

    Cura prepares your model for 3D printing. For novices, it makes it easy to
    get great results. For experts, there are over 200 settings to adjust to
    your needs. As it's open source, our community helps enrich it even more.
builddeps  :
    - python-uranium
    - python-pytest
rundeps    :
    - curaengine
    - python-pyserial
    - python-uranium
    - python-zeroconf
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    # https://github.com/Ultimaker/Cura/issues/2954
    python3 -m pytest -v -k "not TestCuraContainerRegistry and not TestExtruderStack and not TestGlobalStack"
