name       : cura
version    : 4.9.1
release    : 23
source     :
    - https://github.com/Ultimaker/Cura/archive/4.9.1.tar.gz : 087186b93e69b2393cba72d7deb1be77037ccfb34da88cc281e4ca68ef2a2639
license    : LGPL-3.0-or-later
component  : office
summary    : 3D printer / slicing control software
description: |
    Cura is a project which aims to be an single software solution for 3D printing. While it is developed to be used with the Ultimaker 3D printer, it can be used with other RepRap based designs.

    Cura prepares your model for 3D printing. For novices, it makes it easy to get great results. For experts, there are over 200 settings to adjust to your needs. As it's open source, our community helps enrich it even more.
builddeps  :
    - pkgconfig(python3)
    - libsavitar-devel
    - python-uranium
    - python-pynest2d
    - python-pytest
    - python-requests
rundeps    :
    - curaengine
    - fdm-materials
    - libsavitar
    - python-certifi
    - python-keyring
    - python-pynest2d
    - python-pyserial
    - python-requests
    - python-uranium
    - python-zeroconf
setup      : |
    # see https://github.com/Ultimaker/Cura/issues/5142
    %cmake_ninja -DCURA_VERSION=$version \
        -DCURA_CLOUD_API_VERSION=1 \
        -DCURA_CLOUD_API_ROOT="https://api.ultimaker.com" \
        -DCURA_CLOUD_ACCOUNT_API_ROOT="https://account.ultimaker.com" \
        -DCURA_SDK_VERSION=6.0.0
build      : |
    %ninja_build
install    : |
    %ninja_install

    # for better performances
    %qml_cache
    %python3_compile
#check      : |
#    %python3_test py.test3 -v
