name       : cura
version    : 3.5.1
release    : 9
source     :
    - https://github.com/Ultimaker/Cura/archive/3.5.1.tar.gz : eda9586f46fa506426fe8eec5c6527581d67ef2ffd5bf9a6306447a39be96424
license    : LGPL-3.0-or-later
component  : office
summary    : 3D printer / slicing control software
description: |
    Cura is a project which aims to be an single software solution for 3D
    printing. While it is developed to be used with the Ultimaker 3D printer,
    it can be used with other RepRap based designs.

    Cura prepares your model for 3D printing. For novices, it makes it easy to
    get great results. For experts, there are over 200 settings to adjust to
    your needs. As it's open source, our community helps enrich it even more.
builddeps  :
    - libsavitar-devel
    - python-uranium
    - python-pytest
rundeps    :
    - curaengine
    - fdm-materials
    - libsavitar
    - python-pyserial
    - python-uranium
    - python-zeroconf
    - qt5-quickcontrols2
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # for better performances
    %qml_cache
    %python3_compile
check      : |
    python3 -m pytest -v
