name       : cura
version    : 3.6.0
release    : 10
source     :
    - https://github.com/Ultimaker/Cura/archive/3.6.0.tar.gz : c3f9a93c16cd2d082d871448d2763e69955735f73be79dd3528b36a03cfb30c0
license    : LGPL-3.0-or-later
component  : office
summary    : 3D printer / slicing control software
description: |
    Cura is a project which aims to be an single software solution for 3D
    printing. While it is developed to be used with the Ultimaker 3D printer,
    it can be used with other RepRap based designs.

    Cura prepares your model for 3D printing. For novices, it makes it easy to
    get great results. For experts, there are over 200 settings to adjust to
    your needs. As it's open source, our community helps enrich it even more.
builddeps  :
    - libsavitar-devel
    - python-uranium
    - python-pytest
    - python-requests
rundeps    :
    - curaengine
    - fdm-materials
    - libsavitar
    - python-pyserial
    - python-uranium
    - python-zeroconf
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install

    # for better performances
    %qml_cache
    %python3_compile
#check      : |
#    %python3_test py.test3 -v
