name       : cura
version    : 4.3.0
release    : 16
source     :
    - https://github.com/Ultimaker/Cura/archive/4.3.0.tar.gz : a27f5671250452d685069d8fe8018438ec32c096cd5b2c0d54ada7022ded1ccf
license    : LGPL-3.0-or-later
component  : office
summary    : 3D printer / slicing control software
description: |
    Cura is a project which aims to be an single software solution for 3D printing. While it is developed to be used with the Ultimaker 3D printer, it can be used with other RepRap based designs.

    Cura prepares your model for 3D printing. For novices, it makes it easy to get great results. For experts, there are over 200 settings to adjust to your needs. As it's open source, our community helps enrich it even more.
builddeps  :
    - pkgconfig(python3)
    - libsavitar-devel
    - python-uranium
    - python-pytest
    - python-requests
rundeps    :
    - curaengine
    - fdm-materials
    - libsavitar
    - python-pyserial
    - python-requests
    - python-uranium
    - python-zeroconf
setup      : |
    # see https://github.com/Ultimaker/Cura/issues/5142
    %cmake_ninja -DCURA_VERSION=$version \
        -DCURA_CLOUD_API_VERSION=1 \
        -DCURA_SDK_VERSION=6.0.0
build      : |
    %ninja_build
install    : |
    %ninja_install

    # for better performances
    %qml_cache
    %python3_compile
check      : |
    %python3_test py.test3 -v
