name       : cura
version    : 3.2.1
release    : 5
source     :
    - https://github.com/Ultimaker/Cura/archive/3.2.1.tar.gz : 23ef0f0670bc55ec3a6feed565e38a7e37136dd05ab5c202df6656aa24a5bbcb
license    : LGPL-3.0
component  : office
summary    : 3D printer / slicing control software
description: |
    Cura is a project which aims to be an single software solution for 3D
    printing. While it is developed to be used with the Ultimaker 3D printer,
    it can be used with other RepRap based designs.

    Cura prepares your model for 3D printing. For novices, it makes it easy to
    get great results. For experts, there are over 200 settings to adjust to
    your needs. As it's open source, our community helps enrich it even more.
builddeps  :
    - python-uranium
    - python-pytest
rundeps    :
    - curaengine
    - python-pyserial
    - python-uranium
    - python-zeroconf
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
check      : |
    python3 -m pytest -v -k "not TestExtruderStack"

