name       : cura
version    : 4.6.2
release    : 20
source     :
    - https://github.com/Ultimaker/Cura/archive/4.6.2.tar.gz : a6bcbf15bcc36d2c6bbedc9d52c7b00b7e22f3e44ca53b0ca7c73b8c1f49bb80
license    : LGPL-3.0-or-later
component  : office
summary    : 3D printer / slicing control software
description: |
    Cura is a project which aims to be an single software solution for 3D printing. While it is developed to be used with the Ultimaker 3D printer, it can be used with other RepRap based designs.

    Cura prepares your model for 3D printing. For novices, it makes it easy to get great results. For experts, there are over 200 settings to adjust to your needs. As it's open source, our community helps enrich it even more.
builddeps  :
    - pkgconfig(python3)
    - libsavitar-devel
    - python-uranium
    - python-pytest
    - python-requests
rundeps    :
    - curaengine
    - fdm-materials
    - libsavitar
    - python-pyserial
    - python-requests
    - python-uranium
    - python-zeroconf
setup      : |
    %patch -p1 < $pkgfiles/Prevent-crash-when-camera-tool-was-not-found.patch

    # see https://github.com/Ultimaker/Cura/issues/5142
    %cmake_ninja -DCURA_VERSION=$version \
        -DCURA_CLOUD_API_VERSION=1 \
        -DCURA_CLOUD_API_ROOT="https://api.ultimaker.com" \
        -DCURA_CLOUD_ACCOUNT_API_ROOT="https://account.ultimaker.com" \
        -DCURA_SDK_VERSION=6.0.0
build      : |
    %ninja_build
install    : |
    %ninja_install

    # for better performances
    %qml_cache
    %python3_compile
check      : |
    %python3_test py.test3 -v
