name       : cura
version    : 3.3.1
release    : 6
source     :
    - https://github.com/Ultimaker/Cura/archive/3.3.1.tar.gz : 275cecbb20df9b52c404747e10010ace31ce3ee4c4ffa4322343fd1de5f789fb
license    : LGPL-3.0-or-later
component  : office
summary    : 3D printer / slicing control software
description: |
    Cura is a project which aims to be an single software solution for 3D
    printing. While it is developed to be used with the Ultimaker 3D printer,
    it can be used with other RepRap based designs.

    Cura prepares your model for 3D printing. For novices, it makes it easy to
    get great results. For experts, there are over 200 settings to adjust to
    your needs. As it's open source, our community helps enrich it even more.
builddeps  :
    - python-uranium
    - python-pytest
rundeps    :
    - curaengine
    - python-pyserial
    - python-uranium
    - python-zeroconf
    - qt5-quickcontrols2
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install

    # for better performances
    %qml_cache
    %python3_compile
check      : |
    python3 -m pytest -v -k "not test_addContainerExtruderStack and not test_addContainerGlobalStack"
